import 'dotenv/config';
import express from 'express';
import session from 'express-session';
import pg from 'pg';
import connectPgSimple from 'connect-pg-simple';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const { Pool } = pg;
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const app = express();
const PORT = Number(process.env.PORT || 3000);
const CHANNEL = (process.env.TWITCH_CHANNEL || 'wariouss').toLowerCase();
const POINTS_PER_MINUTE = Math.max(1, Number(process.env.POINTS_PER_MINUTE || 10));

function twitchRedirectUri(req){
  const host = (req.hostname || '').toLowerCase();
  if(host === 'localhost') return process.env.TWITCH_REDIRECT_URI_LOCAL || `http://localhost:${PORT}/auth/twitch/callback`;
  return process.env.TWITCH_REDIRECT_URI_PUBLIC || requireEnv('TWITCH_REDIRECT_URI');
}
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: process.env.NODE_ENV === 'production' ? { rejectUnauthorized: false } : false });
const PgStore = connectPgSimple(session);
app.set('trust proxy', 1);
app.use(helmet({ contentSecurityPolicy: false }));
app.use(express.json({ limit: '1mb' }));
app.use(express.urlencoded({ extended: false }));
app.use(session({store:new PgStore({pool,createTableIfMissing:true}),secret:process.env.SESSION_SECRET||'dev-only-change-me',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:1000*60*60*24*30}}));
app.use('/api',rateLimit({windowMs:60000,limit:120,standardHeaders:'draft-8',legacyHeaders:false}));
let appToken=null,appTokenExpiresAt=0;
function requireEnv(name){if(!process.env[name])throw new Error(`Missing ${name}`);return process.env[name];}
function isAdmin(req){return !!req.session.user?.twitchId&&(process.env.ADMIN_TWITCH_IDS||'').split(',').map(x=>x.trim()).filter(Boolean).includes(req.session.user.twitchId);}
function requireAuth(req,res,next){if(!req.session.user)return res.status(401).json({error:'Нужно войти через Twitch'});next();}
function requireAdmin(req,res,next){if(!isAdmin(req))return res.status(403).json({error:'Нет доступа'});next();}
function publicUser(row){return{id:row.id,twitch_id:row.twitch_id,display_name:row.display_name,avatar_url:row.custom_avatar_url||row.avatar_url||'',points:Number(row.points),vp:Number(row.vp),watch_seconds:Number(row.watch_seconds),redeemed:Number(row.redeemed_count),level:Math.max(1,Math.floor(Number(row.watch_seconds)/3600)+1)};}
async function twitchToken(){if(appToken&&Date.now()<appTokenExpiresAt-60000)return appToken;const client_id=requireEnv('TWITCH_CLIENT_ID'),client_secret=requireEnv('TWITCH_CLIENT_SECRET');const r=await fetch('https://id.twitch.tv/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id,client_secret,grant_type:'client_credentials'})});if(!r.ok)throw new Error('Twitch app token failed');const d=await r.json();appToken=d.access_token;appTokenExpiresAt=Date.now()+d.expires_in*1000;return appToken;}
async function twitchApi(url,token){const r=await fetch(url,{headers:{'Client-Id':requireEnv('TWITCH_CLIENT_ID'),'Authorization':`Bearer ${token}`}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||'Twitch API error');return d;}
async function getLive(){const token=await twitchToken();const d=await twitchApi(`https://api.twitch.tv/helix/streams?user_login=${encodeURIComponent(CHANNEL)}`,token);return d.data?.[0]||null;}
app.get('/auth/twitch',(req,res)=>{try{const state=crypto.randomBytes(24).toString('hex');req.session.oauthState=state;const qs=new URLSearchParams({client_id:requireEnv('TWITCH_CLIENT_ID'),redirect_uri:twitchRedirectUri(req),response_type:'code',scope:'user:read:email',state});res.redirect(`https://id.twitch.tv/oauth2/authorize?${qs}`);}catch(e){res.status(500).send(e.message)}});
app.get('/auth/twitch/callback',async(req,res)=>{try{if(!req.query.code||!req.query.state||req.query.state!==req.session.oauthState)return res.status(400).send('OAuth state invalid');delete req.session.oauthState;const client_id=requireEnv('TWITCH_CLIENT_ID'),client_secret=requireEnv('TWITCH_CLIENT_SECRET'),redirect_uri=twitchRedirectUri(req);const tokenRes=await fetch('https://id.twitch.tv/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id,client_secret,code:req.query.code,grant_type:'authorization_code',redirect_uri})});const token=await tokenRes.json();if(!tokenRes.ok)throw new Error(token.message||'OAuth token exchange failed');const validateRes=await fetch('https://id.twitch.tv/oauth2/validate',{headers:{Authorization:`OAuth ${token.access_token}`}});const valid=await validateRes.json();if(!validateRes.ok)throw new Error('Twitch token validation failed');const userData=await twitchApi(`https://api.twitch.tv/helix/users?id=${encodeURIComponent(valid.user_id)}`,token.access_token);const t=userData.data?.[0];if(!t)throw new Error('Twitch user not found');const {rows}=await pool.query(`INSERT INTO users(twitch_id,login,display_name,avatar_url) VALUES($1,$2,$3,$4) ON CONFLICT(twitch_id) DO UPDATE SET login=EXCLUDED.login,display_name=EXCLUDED.display_name,avatar_url=EXCLUDED.avatar_url,updated_at=NOW() RETURNING *`,[t.id,t.login,t.display_name,t.profile_image_url]);req.session.user={id:rows[0].id,twitchId:t.id};res.redirect('/');}catch(e){res.status(500).send(`Twitch login failed: ${e.message}`)}});
app.post('/auth/logout',async(req,res)=>{req.session.destroy(()=>res.json({ok:true}));});
app.get('/api/me',requireAuth,async(req,res)=>{const {rows}=await pool.query('SELECT * FROM users WHERE id=$1',[req.session.user.id]);if(!rows[0])return req.session.destroy(()=>res.status(401).json({error:'Пользователь не найден'}));res.json({user:publicUser(rows[0])});});
app.get('/api/live',async(req,res)=>{try{const s=await getLive();res.json({live:!!s,stream:s?{title:s.title,game:s.game_name,viewers:s.viewer_count,started_at:s.started_at}:null});}catch(e){res.status(502).json({error:e.message});}});
app.get('/api/rewards',async(req,res)=>{const {rows}=await pool.query('SELECT * FROM rewards WHERE active=true ORDER BY sort_order,id');res.json({rewards:rows.map(r=>({id:r.id,vp:r.vp,cost:Number(r.cost)}))});});
app.get('/api/leaderboard',async(req,res)=>{const {rows}=await pool.query('SELECT id,display_name,points,avatar_url,custom_avatar_url FROM users ORDER BY points DESC,id ASC LIMIT 10');res.json({users:rows.map(r=>({id:r.id,display_name:r.display_name,avatar_url:r.custom_avatar_url||r.avatar_url||'',points:Number(r.points)}))});});
app.post('/api/profile/avatar',requireAuth,async(req,res)=>{const avatar=typeof req.body.avatar==='string'?req.body.avatar:'';if(!avatar)return res.status(400).json({error:'Аватар не выбран'});if(!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(avatar))return res.status(400).json({error:'Неверный формат аватара'});if(avatar.length>250000)return res.status(413).json({error:'Картинка слишком большая'});const {rows}=await pool.query('UPDATE users SET custom_avatar_url=$1,updated_at=NOW() WHERE id=$2 RETURNING *',[avatar,req.session.user.id]);if(!rows[0])return res.status(404).json({error:'Пользователь не найден'});res.json({user:publicUser(rows[0])});});
app.delete('/api/profile/avatar',requireAuth,async(req,res)=>{const {rows}=await pool.query('UPDATE users SET custom_avatar_url=NULL,updated_at=NOW() WHERE id=$1 RETURNING *',[req.session.user.id]);if(!rows[0])return res.status(404).json({error:'Пользователь не найден'});res.json({user:publicUser(rows[0])});});
async function closeActiveWatch(client,userId){const {rows}=await client.query(`SELECT * FROM watch_sessions WHERE user_id=$1 AND active=true ORDER BY id DESC LIMIT 1 FOR UPDATE`,[userId]);if(!rows[0])return null;const s=rows[0],elapsed=Math.max(0,Math.min(120,Math.floor((Date.now()-new Date(s.last_heartbeat_at).getTime())/1000))),points=Math.floor(elapsed/60)*POINTS_PER_MINUTE;await client.query('UPDATE watch_sessions SET active=false,ended_at=NOW(),credited_seconds=credited_seconds+$1 WHERE id=$2',[elapsed,s.id]);if(points>0){await client.query('UPDATE users SET points=points+$1,watch_seconds=watch_seconds+$2,updated_at=NOW() WHERE id=$3',[points,elapsed,userId]);await client.query('INSERT INTO transactions(user_id,type,points_delta,metadata) VALUES($1,\'watch\',$2,$3)',[userId,points,JSON.stringify({seconds:elapsed})]);}return{points,credit:elapsed};}
app.post('/api/watch/start',requireAuth,async(req,res)=>{const live=await getLive().catch(()=>null);if(!live)return res.status(409).json({error:'Сейчас wariouss не в эфире'});const client=await pool.connect();try{await client.query('BEGIN');await client.query('UPDATE watch_sessions SET active=false,ended_at=NOW() WHERE user_id=$1 AND active=true',[req.session.user.id]);const {rows}=await client.query('INSERT INTO watch_sessions(user_id) VALUES($1) RETURNING *',[req.session.user.id]);await client.query('COMMIT');res.json({id:rows[0].id,elapsed_seconds:0});}catch(e){await client.query('ROLLBACK');res.status(500).json({error:e.message});}finally{client.release();}});
app.post('/api/watch/heartbeat',requireAuth,async(req,res)=>{const live=await getLive().catch(()=>null);if(!live)return res.status(409).json({error:'Эфир завершён'});const client=await pool.connect();try{await client.query('BEGIN');const {rows}=await client.query('SELECT * FROM watch_sessions WHERE user_id=$1 AND active=true ORDER BY id DESC LIMIT 1 FOR UPDATE',[req.session.user.id]);if(!rows[0]){await client.query('ROLLBACK');return res.status(409).json({error:'Сессия просмотра не активна'});}const s=rows[0],elapsed=Math.max(0,Math.min(120,Math.floor((Date.now()-new Date(s.last_heartbeat_at).getTime())/1000))),points=Math.floor(elapsed/60)*POINTS_PER_MINUTE;await client.query('UPDATE watch_sessions SET last_heartbeat_at=NOW(),credited_seconds=credited_seconds+$1 WHERE id=$2',[elapsed,s.id]);if(points>0){await client.query('UPDATE users SET points=points+$1,watch_seconds=watch_seconds+$2,updated_at=NOW() WHERE id=$3',[points,elapsed,req.session.user.id]);await client.query('INSERT INTO transactions(user_id,type,points_delta,metadata) VALUES($1,\'watch\',$2,$3)',[req.session.user.id,points,JSON.stringify({seconds:elapsed})]);}const u=await client.query('SELECT * FROM users WHERE id=$1',[req.session.user.id]);await client.query('COMMIT');res.json({user:publicUser(u.rows[0]),watch:{id:s.id,elapsed_seconds:Number(s.credited_seconds)+elapsed}});}catch(e){await client.query('ROLLBACK');res.status(500).json({error:e.message});}finally{client.release();}});
app.post('/api/watch/stop',requireAuth,async(req,res)=>{const client=await pool.connect();try{await client.query('BEGIN');await closeActiveWatch(client,req.session.user.id);const u=await client.query('SELECT * FROM users WHERE id=$1',[req.session.user.id]);await client.query('COMMIT');res.json({user:publicUser(u.rows[0])});}catch(e){await client.query('ROLLBACK');res.status(500).json({error:e.message});}finally{client.release();}});
app.post('/api/redeem',requireAuth,async(req,res)=>{const rewardId=Number(req.body.rewardId);if(!Number.isInteger(rewardId))return res.status(400).json({error:'Неверная награда'});const client=await pool.connect();try{await client.query('BEGIN');const r=await client.query('SELECT * FROM rewards WHERE id=$1 AND active=true FOR UPDATE',[rewardId]);if(!r.rows[0])throw new Error('Награда не найдена');const reward=r.rows[0],u=await client.query('SELECT * FROM users WHERE id=$1 FOR UPDATE',[req.session.user.id]);if(Number(u.rows[0].points)<Number(reward.cost))throw new Error('НЕДОСТАТОЧНО ОЧКОВ');await client.query('UPDATE users SET points=points-$1,vp=vp+$2,redeemed_count=redeemed_count+1,updated_at=NOW() WHERE id=$3',[reward.cost,reward.vp,req.session.user.id]);await client.query('INSERT INTO transactions(user_id,type,points_delta,vp_delta,reward_id) VALUES($1,\'redeem\',$2,$3,$4)',[req.session.user.id,-Number(reward.cost),Number(reward.vp),reward.id]);const nu=await client.query('SELECT * FROM users WHERE id=$1',[req.session.user.id]);await client.query('COMMIT');res.json({user:publicUser(nu.rows[0])});}catch(e){await client.query('ROLLBACK');res.status(409).json({error:e.message});}finally{client.release();}});
app.post('/api/redeem/quick',requireAuth,async(req,res)=>{const {rows}=await pool.query('SELECT * FROM rewards WHERE active=true ORDER BY cost ASC');const client=await pool.connect();try{await client.query('BEGIN');const u=await client.query('SELECT * FROM users WHERE id=$1 FOR UPDATE',[req.session.user.id]),reward=rows.find(x=>Number(u.rows[0].points)>=Number(x.cost));if(!reward)throw new Error('НЕДОСТАТОЧНО ОЧКОВ');await client.query('UPDATE users SET points=points-$1,vp=vp+$2,redeemed_count=redeemed_count+1,updated_at=NOW() WHERE id=$3',[reward.cost,reward.vp,req.session.user.id]);await client.query('INSERT INTO transactions(user_id,type,points_delta,vp_delta,reward_id) VALUES($1,\'redeem\',$2,$3,$4)',[req.session.user.id,-Number(reward.cost),Number(reward.vp),reward.id]);const nu=await client.query('SELECT * FROM users WHERE id=$1',[req.session.user.id]);await client.query('COMMIT');res.json({user:publicUser(nu.rows[0])});}catch(e){await client.query('ROLLBACK');res.status(409).json({error:e.message});}finally{client.release();}});
app.get('/admin',requireAdmin,(req,res)=>res.sendFile(path.join(__dirname,'public','admin.html')));
app.get('/api/admin/stats',requireAdmin,async(req,res)=>{const[users,points,vp,tx]=await Promise.all([pool.query('SELECT COUNT(*)::int count FROM users'),pool.query('SELECT COALESCE(SUM(points),0)::bigint sum FROM users'),pool.query('SELECT COALESCE(SUM(vp),0)::bigint sum FROM users'),pool.query('SELECT COUNT(*)::int count FROM transactions')]);res.json({users:Number(users.rows[0].count),points:Number(points.rows[0].sum),vp:Number(vp.rows[0].sum),transactions:Number(tx.rows[0].count)});});
app.get('/api/admin/users',requireAdmin,async(req,res)=>{const {rows}=await pool.query('SELECT id,twitch_id,login,display_name,points,vp,watch_seconds,redeemed_count FROM users ORDER BY points DESC LIMIT 100');res.json({users:rows.map(publicUser)});});
app.post('/api/admin/users/:id/vp/reset',requireAdmin,async(req,res)=>{const client=await pool.connect();try{await client.query('BEGIN');const u=await client.query('SELECT * FROM users WHERE id=$1 FOR UPDATE',[req.params.id]);if(!u.rows[0])throw new Error('Пользователь не найден');const oldVp=Number(u.rows[0].vp);await client.query('UPDATE users SET vp=0,updated_at=NOW() WHERE id=$1',[req.params.id]);if(oldVp!==0)await client.query('INSERT INTO transactions(user_id,type,vp_delta,metadata) VALUES($1,\'admin_vp_reset\',$2,$3)',[req.params.id,-oldVp,JSON.stringify({admin:req.session.user.twitchId,previous_vp:oldVp})]);await client.query('COMMIT');res.json({ok:true,previous_vp:oldVp});}catch(e){await client.query('ROLLBACK');res.status(409).json({error:e.message});}finally{client.release();}});
app.post('/api/admin/users/:id/points',requireAdmin,async(req,res)=>{const delta=Number(req.body.delta);if(!Number.isInteger(delta)||Math.abs(delta)>100000000)return res.status(400).json({error:'Неверное значение'});const client=await pool.connect();try{await client.query('BEGIN');const u=await client.query('SELECT * FROM users WHERE id=$1 FOR UPDATE',[req.params.id]);if(!u.rows[0])throw new Error('Пользователь не найден');if(Number(u.rows[0].points)+delta<0)throw new Error('Баланс не может быть отрицательным');await client.query('UPDATE users SET points=points+$1,updated_at=NOW() WHERE id=$2',[delta,req.params.id]);await client.query('INSERT INTO transactions(user_id,type,points_delta,metadata) VALUES($1,\'admin_adjustment\',$2,$3)',[req.params.id,delta,JSON.stringify({admin:req.session.user.twitchId})]);await client.query('COMMIT');res.json({ok:true});}catch(e){await client.query('ROLLBACK');res.status(409).json({error:e.message});}finally{client.release();}});
app.get('/api/admin/transactions',requireAdmin,async(req,res)=>{const {rows}=await pool.query(`SELECT t.id,t.type,t.points_delta,t.vp_delta,t.created_at,u.display_name FROM transactions t JOIN users u ON u.id=t.user_id ORDER BY t.created_at DESC LIMIT 100`);res.json({transactions:rows});});
app.post('/api/admin/rewards',requireAdmin,async(req,res)=>{const id=Number(req.body.id),cost=Number(req.body.cost),vp=Number(req.body.vp);if(!Number.isInteger(id)||cost<=0||vp<=0)return res.status(400).json({error:'Неверные данные'});await pool.query('UPDATE rewards SET cost=$1,vp=$2 WHERE id=$3',[cost,vp,id]);res.json({ok:true});});
app.use(express.static(path.join(__dirname,'public')));
async function boot(){if(!process.env.DATABASE_URL)console.warn('DATABASE_URL is not set.');if(fs.existsSync(path.join(__dirname,'sql','schema.sql'))){const sql=fs.readFileSync(path.join(__dirname,'sql','schema.sql'),'utf8');await pool.query(sql);}await pool.query('ALTER TABLE users ADD COLUMN IF NOT EXISTS custom_avatar_url TEXT');app.listen(PORT,()=>console.log(`wariouss.vp running on http://localhost:${PORT}`));}
boot().catch(err=>{console.error(err);process.exit(1)});